import React from 'react';
import '../index.css';
import InfiniteScroll from '../LoadMore/index.js';

export default class Shop extends React.Component {
    render() {
        return (
            <div className="content">
                <h1 className="title">Infinite Scroll React</h1>
                <p className="description">
                    Each Avatar is generated in the same position on load.
                    Avatar names are randomly generated by an object oriented function.
                    The Avatars likes are generated by a similar object oriented function.  
                </p>
                <div className="avatars" id="avatars"><InfiniteScroll/></div>
            </div>
            
        );
    }
}